id = "viewtree"
name = "View Tree Syntax Highlighting for $mol"
version = "0.0.2"
schema_version = 1
authors = ["Kirill Novgorodtsev kirrallt@mail.ru"]
description = "Syntax higlighting for .tree files in $mol web framework"
repository = "https://github.com/dev-cmyser/zed-tree-mol-support"

[grammars.gleam]
repository = "https://github.com/Dev-cmyser/tree-sitter-mol-view-tree"
rev = "ee1dd85b8217080964eaa5b25823f1fb1915bbf3"
