id = "view.tree"
name = "View Tree Syntax Highlighting for $mol"
version = "0.0.1"
schema_version = 1
authors = ["Kirill Novgorodtsev kirrallt@mail.ru"]
description = "Syntax higlighting for .tree files in $mol web framework"
repository = "https://github.com/dev-cmyser/zed-tree-mol-support"
