id = "viewtree"
name = "View Tree Syntax Highlighting for $mol"
version = "0.0.3"
schema_version = 1
authors = ["Kirill Novgorodtsev kirrallt@mail.ru"]
description = "Syntax higlighting for view.tree files in $mol web framework"
repository = "https://github.com/dev-cmyser/zed-tree-mol-support"

[grammars.molviewtree]
repository = "https://github.com/Dev-cmyser/tree-sitter-mol-view-tree"
commit = "ac820a7936a7173ef1bc6b3b8750cc1bf927ca4b"
